config/routes.rb
Rails.application.routes.draw do
 	root "welcome#home"
 	get "about" , to: "welcome#about"
 	resources :articles
  get 'signup' , to: 'users#new'
  resources :users , except:[:new]
  get 'login' , to: "sessions#new"
  post 'login' , to: "sessions#create"
  delete 'logout' , to: "sessions#destroy"
  



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
validates :title , presence: true , length:{minimum: 3 , maximum: 20}
validates :description ,presence: true , length:{minimum:10 , maximum: 100}

  validates :user_id , presence: true


end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles
  before_save{self.email = email.downcase}
  validates :username, presence: true ,uniqueness:{case_sensitive: false}, length:{minimum: 3 , maximum: 25}
  VALID_EMAIL_REGEX = /^\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email ,presence: true , uniqueness:{case_sensitive: false} ,length:{maximum: 105} , format: {with: VALID_EMAIL_REGEX , multiline: true}
  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user , :logged_in? 
    def current_user
       @current_user ||=  User.find(session[:user_id]) if session[:user_id]
       

    end

    def logged_in?
        !!@current_user
    end

    def require_user
        if !logged_in?
            flash[:danger] = "You must be logged in to perform that action."
            redirect_to root_path
        end
    end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :set_param , only:[:edit , :update , :show , :destroy]
	def index
		@articles = Article.paginate(page: params[:page],per_page: 5)



	end

	def new
		@article = Article.new

	end

	def create
    debugger
		#render plain: params[:artilce].inspect
    @article = Article.new(article_params)
    @article.user = User.first
		if @article.save
			flash[:success] = "Article was successfully created"
		   redirect_to article_path(@article)
		else
			render :new
		end



	end
	def edit
		

	end
	def update
		
		if @article.update(article_params)
			flash[:success] = "Article was successfully updated"
			redirect_to article_path
		else
			render :edit
		end

	end

	def show
		
		
	end
	def destroy
		
		@article.destroy
		flash[:danger] = "Article was successfully deleted"
		redirect_to articles_path
	end

	private
	def set_param
		@article = Article.find(params[:id])
	end
	def article_params
		params.require(:article).permit(:title , :description)

	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        #render 'new'
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
        flash[:success] = "You have successfully loged in."
        redirect_to user_path(user)
        session[:user_id] = user.id


        else
        flash.now[:danger] = "There was something wrong with your login information. "

        render 'new'


        end



    end

    def destroy
        session[:user_id] = nil
        flash[:success] = "You have loged out."
        redirect_to root_path


    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user , only: [:edit , :update , :show]

  def index
    @users = User.paginate(page: params[:page] , per_page: 5 )



  end
  def new
    @user = User.new

  end

  def create
    @user = User.new(user_params)

    if @user.save

      flash[:success] = "Welcome to alpha blog #{@user.username}"
      redirect_to articles_path



    else

      render 'new'




    end


  end

  def edit
    

  end


  def update
    
    if @user.update(user_params)
      flash[:success] = "Your account was updated successfully."
      redirect_to articles_path



    else
      render 'edit'

    end

  end

  def show
    
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)



  end

  private
  def user_params
    params.require(:user).permit(:username , :email , :password)


  end
  def set_user
    @user = User.find(params[:id])
    
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def home
	end
	def about
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user,options={size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url,alt: user.username,class: "rounded-circle")

  end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
    <div class="row">
        <div class="col-5 offset-md-3">
            <div class="shadow-lg p-3 mb-5 bg-white rounded">
                <div class="article-title">
                    <%= link_to  article.title , article_path(article) %>
                </div>
                <div class="article-body">
	 	                <%= truncate(article.description , length: 100 ) %>
                    <div class="article-meta-details">
                    <small>Created by: <%= article.user.username if article.user %>,
                        <%= time_ago_in_words(article.created_at) %> ago,
                        last updated: <%= time_ago_in_words(article.updated_at) %> ago </small>



                    </div>
                </div>
                <div class="article-actions">
                    <%= link_to "Edit this article" , edit_article_path(article),class: "btn btn-sm btn-primary" %>
                    <%= link_to "Delete this article" , article_path(article), method: :delete , data:{confirm: "Are you sure you want to delete?"} , class: "btn btn-sm btn-danger" %>

                </div>
            </div>
        </div>
    </div>


<% end %>

app/views/articles/_form.html.erb
<%= render "/shared/errors" , obj: @article %>

<div class="container">
          <div class="col-xs-12">



<%= form_for @article  do |f| %>
    <div class="form-group">
        <label for="Exampletitle">Title</label>

            <%= f.text_field :title , class: "form-control" , placeholder: "Title of article" , autofocus: true , id: "Exampletitle" %>

    </div>

    <div class="form-group">

    <label for="Exampledescription">Description</label>
    <%= f.text_area :description ,rows: 10, class: "form-control" , placeholder: "Description of article" , autofocus: true , id: "Exampledescription" %><br />
    </div>
    <div class="form-group">
	      <%= f.submit  class: "btn btn-primary btn-lg" %>
    </div>
<% end %>
          </div>
</div>
<div class="col-xs-4 col-xs-offset-4">
[ <%= link_to "Cancel request  and return to articles listing" , articles_path %> ]
</div>

app/views/articles/edit.html.erb
<h1 align="center" class="htn">Edit exsisting article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center"> Listing all articles </h1>
<div class="center">
        <%= will_paginate%>
</div>

<%= render 'article', obj:@articles %>

app/views/articles/new.html.erb
<h1 align="center" class="htn">Create new article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center"> Title: <%= @article.title %></h2>
<div class="row">
    <div class="alert alert-secondary col-sm-8 offset-md-3">
        <% if @article.user %>
    <ul class="listing">
        <div class="row justify-content-center" align="center">
            <div class= "col-md-4 col-md-offset-4 ">
                <li>Created_by: </li>
                <li> <%= link_to gravatar_for(@article.user) , user_path(@article.user) %></li>
                <li class="article-title">
                    <%= link_to @article.user.username ,user_path(@article.user) %>
                </li>
                <li><small><%= pluralize(@article.user.articles.count , "article") if @article.user.articles %></small></li>
            </div>
        </div>
    </ul>
    <% end %>
    <h4 class="center descriptions"><strong>Description:</strong></h4>
    <hr>

    <%= simple_format(@article.description) %>
    <div class="article-actions">
        <%= link_to "Edit this article" , edit_article_path(@article),class: "btn btn-sm btn-primary" %>
        <%= link_to "Delete this article" , article_path(@article), method: :delete , data:{confirm: "Are you sure you want to delete?"} , class: "btn btn-sm btn-danger" %>
        <%= link_to "View all article" , articles_path , class: "btn btn-sm btn-success" %>

</div>
</div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
	<footer class="footer">
		<small>
			Copyright &copy: <a href="https://www.udemy.com" > The Complate Ruby on Rails Developer</a>
			by <a href="http://www.payman-kazemi.com">Payman kazmei</a>
		</small>
		<nav>
			<ul>
				<li> <%= link_to "About" , about_path %></li>
			</ul>
		</nav>
	</footer>


</div>

app/views/layouts/_messages.html.erb
<div class="row">
    <div class="col-sm-10 col-sm-offset-1">

        <% flash.each do |name,msg| %>
            <div class='alert alert-<%= "#{name}" %>'>
                <a href="#" class="close" data-dismiss="alert">&#215;</a>
                <%= content_tag :div , msg , :id => "flash_#{name}" if msg.is_a?(String) %>
            </div>

       <% end %>
    </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
    
      <li class="nav-item active">
        <%= link_to "Home" , root_path , class: "nav-link"%>
      </li>
      <% if logged_in? %>
     <li class="nav-item">
        <%= link_to "Log out" , logout_path ,method: :delete, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Articles" , articles_path , class: "nav-link" %>
      </li>
      <% else %>
      

       <li class="nav-item">
        <%= link_to "Log in" , login_path , class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign up" , signup_path , class: "nav-link" %>
      </li>
      <% end %>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown link
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
   <%= render 'layouts/messages' %>
   <div class="container">
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>

  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="alert alert-danger">
                <div class="panel-heading">
                    <h2 class="panel-title">
                        <%= pluralize(obj.errors.count , "Error") %>
                        prohibited this article form being saved:
                    </h2>
                    <div class="panel-body">
                        <ul>
                            <% obj.errors.full_messages.each do |msg| %>
                                <li> <%= msg %> </li>

                            <% end %>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

<% end %>

app/views/users/_form.html.erb
<%= render "/shared/errors" , obj: @user %>


<div class="container">
    <div class="col-xs-12">



        <%= form_for @user  do |f| %>
            <div class="form-group">
                <label for="Exampletitle">Username</label>

                <%= f.text_field :username , class: "form-control" , placeholder: "Enter username" , autofocus: true , id: "Exampletitle" %>

            </div>

            <div class="form-group">

                <label for="Exampledescription">Email</label>
                <%= f.email_field :email ,class: "form-control" , placeholder: "asdf@example.com" , autofocus: true , id: "Exampledescription" %><br />
            </div>
            <div class="form-group">

                <label for="Exampledescription">password</label>
                <%= f.password_field :password , class: "form-control" , placeholder: "Enter password" , autofocus: true , id: "Exampledescription" %><br />
            </div>

            <div class="form-group">
	              <%= f.submit(@user.new_record? ? "Sign up" : "Update your account",class: "btn btn-primary btn-lg") %>
            </div>
        <% end %>
    </div>
</div>
<div class="col-xs-4 col-xs-offset-4">
    [ <%= link_to "Cancel request  and return to articles listing" , articles_path %> ]
</div>

app/views/users/edit.html.erb
<h1 align="center">Edit your account</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center"> All alpha Bloggers</h1>
<div align="center">
    <%= will_paginate %>
<% @users.each do |user|  %>
    <ul class="listing">
        <div class="row justify-content-center">
            <div class="alert alert-secondary col-md-4 col-md-offset-4 ">
                <li> <%= link_to gravatar_for(user) , user_path(user) %></li>
                <li class="article-title">
                    <%= link_to user.username ,user_path(user) %>
                </li>
                <li><small><%= pluralize(user.articles.count , "article") if user.articles %></small></li>
            </div>
        </div>
    </ul>

<% end %>
<%= will_paginate %>
</div>

app/views/users/new.html.erb
<h1 align="center">Sign up for alpha blog</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center"> Welcome to <small> <%= @user.username %>'s</small> page </h1>
<div class ="row justify-content-center">
    <div class = "col-md-4 col-md-offset-4 center">
        <%= gravatar_for @user , size: 150 %>
        <small align="center"><%= @user.username %>'s artilces </small>
       



    </div>
</div>
<div class="center">
    <%= will_paginate @user_articles %>
</div>
     <%= render 'articles/article' , obj: @user_articles %>
<div class="center">
    <%= will_paginate @user_articles %>
</div>

app/views/welcome/about.html.erb
<h1>Welcome to about page</h1>
<%= link_to "Home" , root_path %>

app/views/welcome/home.html.erb
<div class="mrgn">
<div class="center jumbotron">
	<h1 class="bld">ALPHA BLOG </h1>
<%= link_to "Sign up now", "#", class: "btn btn-danger btn-lg btn-xlarge"%>
</div>
</div>